### ISSUE TITLE
viz_graph CPK colors cause minor problem

### ISSUE THREAD

**Issue by eahenle** [SimonEnsemble/MolecularGraphKernels.jl#13]
Since we use CPK colors for the fill and outline of atoms, hydrogen is invisible against a white background.

Suggest making the outline of nodes slightly darker than the fill color.

**Comment by SimonEnsemble** [comment]
could put a thin black stroke around each node?
but this library will never include H, will it? I thought the H would be ignored.

**Comment by eahenle** [comment]
Yeah, black outline would work.  H is by default not explicitly represented, but it's not hard to make it happen, e.g. `MetaGraph(smilestomol("H-H"))`.  Will try the outline ideas, see what looks good.
