### ISSUE TITLE
add ability to highlight a set of nodes, in the `viz_graph`.

### ISSUE THREAD

**Issue by SimonEnsemble** [SimonEnsemble/MolecularGraphKernels.jl#30]
this way we can viz cliques in the modular product graph.
not sure exactly how to highlight them.

also make d-edges in the `viz_graph(mpg)` dashed, to show they are fundamentally different.

**Comment by SimonEnsemble** [comment]
parameterize size of `viz_graph`s? so we can show pairs side by side.

**Comment by SimonEnsemble** [comment]
or `viz_graph(g1, g2)`? to put them side-by-side?

**Comment by SimonEnsemble** [comment]
and/or, Xiaoli says: `extract` the induced subgraph from the `dpg` to visualize it. so given set of nodes (a clique), cut out those nodes, but retain all edges between them, and viz it.

**Comment by eahenle** [comment]
- [x] d-edge different appearance
- [x] isomorphic subgraph extraction from MPG
- [ ] ~plot size argument~
- [ ] ~node highlighting~

no args in `gplot` for overall plot size or node highlighting
